name: black

on: [pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          version: 22.3.0
