name: tests

on: [pull_request]

jobs:
  core:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.9"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        env:
          python-version: ${{ matrix.python-version }}
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install --upgrade pip
          python -m pip install .[core_tests]

      - name: Run Unit Tests (pytest)
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
          python-version: ${{ matrix.python-version }}
        run: |
          python -c "import sys; print(sys.version)"
          python -m pytest tests/core
