name: tests

on: [pull_request]

jobs:
  unit:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python pip install -r requirments.txt
          python pip install .[tests]

      - name: Run Unit Tests (pytest)
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
          python-version: ${{ matrix.python-version }}

        run: |
          python -c "import sys; print(sys.version)"
          python -m pytest tests
