name: tests

on: [pull_request]

jobs:
  unit:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          TEST_TOKEN: ${{ secrets.TEST_US_TOKEN }}
          DEBUG_REQUESTS: "FALSE"
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-xdist
          pip install pytest-cov
      - name: Test with pytest
        run: |
          pytest tests
